### ISSUE TITLE
Casaos port

### ISSUE THREAD

**Issue by kaanvur** [WisdomSky/Cloudflared-web#1]
I installed it so I could access Casaos through my own subdomain. I can access the panel running on port 80 But I can't access ports of other applications

**Comment by andreviallon** [comment]
If I'm understanding your problem correctly, you will have to create a new Public Hostname Page for each page. Here's a tutorial on how to do it https://youtu.be/OAeQwdFXsQQ?si=VQX5BskbssVKbIy0&t=1013

**Comment by kaanvur** [comment]
This works, but it is necessary to go through different subdomains for each application and you need to know them because it is still not possible to go through the casaos interface. Maybe a better solution can be produced in the future.
