### ISSUE TITLE
[Sugestion] Add link to Zero Trust in web interface?

### ISSUE THREAD

**Issue by diegocjorge** [WisdomSky/Cloudflared-web#16]
When using the container with CasaOS, it would be more convenient to make changes to hostname settings if we had a link to https://one.dash.cloudflare.com/ right on the app's web interface.

**Comment by WisdomSky** [comment]
Hello @diegocjorge,

It's now available in [`2024.4.0`](https://hub.docker.com/r/wisdomsky/cloudflared-web/tags).
