### ISSUE TITLE
add security to the UI

### ISSUE THREAD

**Issue by torik988** [WisdomSky/Cloudflared-web#19]
I wanted to know if it was possible to add a password to the web Ui to add security and prevent pepole from accesing the control pannel and modifying the tunnel ?

**Comment by WisdomSky** [comment]
Hi @torik988,


Can you elaborate your use case? 
I don't see a convincing reason for adding such additional functionality.

**Comment by torik988** [comment]
Hey, thanks for the fast response :).
For example, I'm self-hosting all my basic services locally on an RPi. 
But other people, such as friends or family, can have access to other services hosted locally (Jellyfin, Nextcloud, Pi-hole) or even public servers open on the web (HTTPd, UptimeKuma...). 
Also, I'm not sure about the safety of every device I connect to the same network as my server. 
This would be more of a feature to prevent people from my home messing things up than a real safety feature.

**Comment by WisdomSky** [comment]
Understandable.

I'll push an update that will allow you to enable Basic Authentication into the web interface. 

Will update you once it's implemented and released.

**Comment by WisdomSky** [comment]
@torik988 

Hello, I apologize for the late update. Basic Auth is now supported starting in `2024.4.1` tag. If you are currently using the same tag, you can just re-pull it to update your local image.
