### ISSUE TITLE
WRN Your version 2023.10.0 is outdated. We recommend upgrading it to 2024.1.2

### ISSUE THREAD

**Issue by ErickPH** [WisdomSky/Cloudflared-web#3]
While installing cloudflared on my CasaOS

`cloudflared  | 2024-01-11T23:39:57Z INF Version 2023.10.0
cloudflared  | 2024-01-11T23:39:57Z INF GOOS: linux, GOVersion: go1.20.6, GoArch: amd64
cloudflared  | 2024-01-11T23:39:57Z INF Settings: map[no-autoupdate:true token:*****]
cloudflared  | 2024-01-11T23:39:57Z INF cloudflared will not automatically update if installed by a package manager.
cloudflared  | 2024-01-11T23:39:57Z WRN Your version 2023.10.0 is outdated. We recommend upgrading it to 2024.1.2`

How do I update your app?

**Comment by WisdomSky** [comment]
Hi, I'm still yet to push an update with the latest cloudflared version. For now, you can still use the 2023.10.0. Once the new update is available, cloudflared-web will notify you from inside the web UI itself that there's a new update.

**Comment by WisdomSky** [comment]
@ErickPH [`wisdomsky/cloudflared-web:2024.1.2`](https://hub.docker.com/r/wisdomsky/cloudflared-web/tags?page=1&name=2024.1.2) is now available.
