### ISSUE TITLE
Multiple tunnels?

### ISSUE THREAD

**Issue by r-freeman** [WisdomSky/Cloudflared-web#4]
Works great for a single tunnel per Docker container, but is there any way to have multiple tunnels per one container?

**Comment by WisdomSky** [comment]
I'm not sure if I understood what you're trying to say. 

By multiple tunnels, you meant connectors from different tunnels? If so, for what reason do you need it?

**Comment by r-freeman** [comment]
Apologies I got it working now, closing issue.
