### ISSUE TITLE
Broken xterm.js

### ISSUE THREAD

**Issue by jimmisavage** [WisdomSky/Cloudflared-web#43]
Cloudflared version 2024.10.1 needed to resolve broken xterm.js

https://github.com/cloudflare/cloudflared/issues/1337

**Comment by WisdomSky** [comment]
[wisdomsky/cloudflared-web:2024.10.1](https://hub.docker.com/layers/wisdomsky/cloudflared-web/2024.10.1/images/sha256-a62e05d8a0f7eead1c1cd257d845ada2e8336b23230cb2471c35297aedc5a49a?context=explore) deployed.

**Comment by jimmisavage** [comment]
Wow, that was quick! Thanks for the help
